### ISSUE TITLE
Update YML

### ISSUE THREAD

**Issue by kelumsampath** [kelumsampath/health_assistant_client#10]
Update build scripts to set build failure if build shows warnings.

**Comment by I3han** [comment]
Hello, Can I work on this?

**Comment by kelumsampath** [comment]
go ahead

**Comment by I3han** [comment]
There is no errors currently so may I should fix another issue

**Comment by kelumsampath** [comment]
still, the build completed with a set of warnings. Fixing warnings in code is better than ignoring them. we need to set CI=True in the build pipeline to address this issue. up to now, this will be not a big issue. will see it later.
