### ISSUE TITLE
Implement Navigation Bar component

### ISSUE THREAD

**Issue by kelumsampath** [kelumsampath/health_assistant_client#12]
![Capture](https://user-images.githubusercontent.com/35989708/95776331-bf349000-0ce1-11eb-936e-1c8f371b633e.PNG)

reading materials:  https://www.youtube.com/watch?v=PwWHL3RyQgk&app=desktop or else

**Comment by zjjiang2** [comment]
Is this Issue still up for grabs? I would like to work on this!

**Comment by kelumsampath** [comment]
@zjjiang2 you can try it. go ahead

**Comment by zjjiang2** [comment]
![NavBar](https://user-images.githubusercontent.com/71283454/97524236-8ef41f00-197a-11eb-976c-3e45efbcaf0b.jpg)
This is what i made based on the video you provided, I made a temporary logo for the Navigation bar.
Please let me know if this is ok.

**Comment by kelumsampath** [comment]
cool, create the PR
