### ISSUE TITLE
React Router to navigate multiple pages

### ISSUE THREAD

**Issue by kelumsampath** [kelumsampath/health_assistant_client#26]
initiate react-router to navigate between pages
reading materials: https://www.golangprograms.com/how-to-create-simple-react-router-to-navigate-multiple-pages.html

**Comment by Dave-mash** [comment]
> initiate react-router to navigate between pages
> reading materials: https://www.golangprograms.com/how-to-create-simple-react-router-to-navigate-multiple-pages.html

Check out my implementation https://github.com/kelumsampath/health_assistant_client/pull/27
